package io.github.snowdrop.jester.test;

import static org.hamcrest.Matchers.is;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Optional;

import org.apache.http.HttpStatus;
import org.hamcrest.Matchers;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.DisabledIfSystemProperty;

import io.github.snowdrop.jester.api.Jester;
import io.github.snowdrop.jester.api.LocalProject;
import io.github.snowdrop.jester.api.RestService;
import io.github.snowdrop.jester.test.samples.ContainerSamples;
import io.github.snowdrop.jester.utils.AwaitilityUtils;
import io.restassured.config.ConnectionConfig;
import io.restassured.config.HttpClientConfig;
import io.restassured.config.RestAssuredConfig;

@Tag("containers")
@Jester
public class LocalProjectLifecycleIT {

    private static final String MY_PROPERTY = "my.property";
    private static final String MY_PROPERTY_EXPECTED_VALUE = "this is a custom property";

    @LocalProject(location = "../" + ContainerSamples.QUARKUS_REST_LOCATION, buildCommands = { "mvn", "clean",
            "install", "-DskipTests", "-Dquarkus.container-image.build=false" }, dockerfile = "../"
                    + ContainerSamples.QUARKUS_REST_LOCATION
                    + "/src/main/docker/Dockerfile.jvm", ports = ContainerSamples.SAMPLES_DEFAULT_PORT, expectedLog = ContainerSamples.QUARKUS_STARTUP_EXPECTED_LOG)
    static RestService greetings = new RestService().withProperty(MY_PROPERTY, MY_PROPERTY_EXPECTED_VALUE);

    @DisabledIfSystemProperty(named = "environment.ci", matches = "true", disabledReason = "In the GitHub runner, this test is flaky")
    @Test
    public void testServiceIsUpAndRunning() {
        thenServiceIsUpAndRunning();
    }

    @Test
    public void testContextId() {
        Assertions.assertNotNull(greetings.getContextId(), "Context ID was not auto generated by the test framework");
    }

    @Test
    public void testServiceLogs() {
        Assertions.assertFalse(greetings.getLogs().isEmpty(), "Logs is empty!");
        greetings.logs().assertContains(ContainerSamples.QUARKUS_STARTUP_EXPECTED_LOG);
        greetings.logs().assertDoesNotContain("This message should not be in the logs");
    }

    @Test
    public void testServiceProperties() {
        Optional<String> property = greetings.getProperty(MY_PROPERTY);
        assertTrue(property.isPresent(), "Property not found in service!");
        assertEquals(MY_PROPERTY_EXPECTED_VALUE, property.get(), "Property value not expected in service!");
    }

    @DisabledIfSystemProperty(named = "environment.ci", matches = "true", disabledReason = "In the GitHub runner, this test is flaky")
    @Test
    public void testStopAndStart() {
        greetings.stop();
        Assertions.assertFalse(greetings.isRunning(), "Service was up and running!");
        greetings.start();
        Assertions.assertTrue(greetings.isRunning(), "Service was not up and running!");
        thenServiceIsUpAndRunning();
    }

    private void thenServiceIsUpAndRunning() {
        AwaitilityUtils.untilAsserted(() -> greetings.given()
                .config(RestAssuredConfig.config()
                        .httpClient(HttpClientConfig.httpClientConfig().reuseHttpClientInstance())
                        .connectionConfig(ConnectionConfig.connectionConfig().closeIdleConnectionsAfterEachResponse()))
                .get(ContainerSamples.SAMPLES_DEFAULT_REST_PATH).then().statusCode(HttpStatus.SC_OK)
                .body(Matchers.is(ContainerSamples.SAMPLES_DEFAULT_REST_PATH_OUTPUT)));
    }
}
